options:
  merge-default-rules: false
rules:
  # {}のスタイル指定 elseと閉じ括弧は同じ行に書く
  brace-style: 1
  # 最終行の改行の強制
  final-newline: 1
  # 16進数を短くできるときは短くする
  hex-length: 1
  # 16進数は小文字で書く
  hex-notation: 1
  # インデントは半角スペース2個でTabは禁止
  indentation: 1
  # カラーキーワード禁止
  no-color-keywords: 1
  # 空のルールセット禁止
  no-empty-rulesets: 1
  # 無効な値の16進数禁止
  no-invalid-hex: 1
  # プロパティでスペルミス禁止
  no-misspelled-properties: 1
  # 末尾のスペース禁止
  no-trailing-whitespace: 1
  # 小数点以下の末尾ゼロ禁止
  no-trailing-zero: 1
  # ユニバーサルセレクタ禁止
  no-universal-selectors: 1
  # セレクタとプロパティは別の行に、1行に1つの宣言
  one-declaration-per-line: 1
  # コロンの後にスペースを入れる
  space-after-colon: 1
  # コンマの後にスペースを入れる
  space-after-comma: 1
  # 演算子前後にスペースを入れる
  space-around-operator: 1
  # { の前にスペースを入れる
  space-before-brace: 1
  # コロンの前にスペースを入れる
  space-before-colon: 1
  # ()の前後にスペースを入れる
  space-between-parens: 1
  # 最後の宣言で末尾のセミコロンの有無を強制
  trailing-semicolon: 1
  # URLを引用符で囲むのを強制
  url-quotes: 1
  # 0の単位なしを強制
  zero-unit: 1
  # マージ可能な状態のセレクタを禁止
  no-mergeable-selectors: 1
  # 小数点の0の省略の禁止
  leading-zero:
    include: false
