plugins:
  - stylelint-order
  - stylelint-scss
defaultSeverity: warning
rules:
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always-single-line
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always-single-line
  block-opening-brace-newline-after: always
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always
  color-hex-case: lower
  color-hex-length: short
  comment-whitespace-inside: always
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-trailing-semicolon: always
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  function-comma-space-before: never
  function-max-empty-lines: 1
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never
  function-whitespace-after: never
  indentation: 2
  length-zero-no-unit: true
  linebreaks: unix
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-space-after: always
  media-query-list-comma-space-before: never
  no-empty-first-line: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  color-named: never
  no-missing-end-of-source-newline: true
  number-leading-zero: never
  number-no-trailing-zeros: true
  property-case: lower
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-list-comma-newline-after: always-multi-line
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-colon-notation: single
  selector-type-case: lower
  shorthand-property-no-redundant-values: true
  unit-case: lower
  value-keyword-case: lower
  value-list-comma-newline-after: always-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  block-no-empty:
    - true
    - severity: error
  color-no-invalid-hex:
    - true
    - severity: error
  comment-no-empty: true
  declaration-block-single-line-max-declarations: 1
  function-calc-no-invalid:
    - true
    - severity: error
  function-calc-no-unspaced-operator: true
  function-url-quotes: always
  max-empty-lines: 1
  no-duplicate-selectors: true
  no-empty-source:
    - true
    - severity: error
  property-no-unknown: true
  selector-max-universal: 1
  string-no-newline: true
  unit-no-unknown: true
  value-list-max-empty-lines: 0
  order/properties-order:
    # Must be first
    - all
    # Position
    - position
    - top
    - right
    - bottom
    - left
    - z-index
    # Display mode
    - box-sizing
    - display
    # Flexible boxes
    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    # Grid layout
    - grid
    - grid-area
    - grid-template
    - grid-template-areas
    - grid-template-rows
    - grid-template-columns
    - grid-row
    - grid-row-start
    - grid-row-end
    - grid-column
    - grid-column-start
    - grid-column-end
    - grid-auto-rows
    - grid-auto-columns
    - grid-auto-flow
    - grid-gap
    - grid-row-gap
    - grid-column-gap
    # Align
    - align-content
    - align-items
    - align-self
    # Justify
    - justify-content
    - justify-items
    - justify-self
    # Order
    - order
    # Box model
    - float
    - width
    - min-width
    - max-width
    - height
    - min-height
    - max-height
    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
    - overflow
    - overflow-x
    - overflow-y
    - -webkit-overflow-scrolling
    - -ms-overflow-x
    - -ms-overflow-y
    - -ms-overflow-style
    - clip
    - clear
    # Typography
    - font
    - font-family
    - font-size
    - font-style
    - font-weight
    - font-variant
    - font-size-adjust
    - font-stretch
    - font-effect
    - font-emphasize
    - font-emphasize-position
    - font-emphasize-style
    - -webkit-font-smoothing
    - -moz-osx-font-smoothing
    - font-smooth
    - hyphens
    - line-height
    - color
    - text-align
    - text-align-last
    - text-emphasis
    - text-emphasis-color
    - text-emphasis-style
    - text-emphasis-position
    - text-decoration
    - text-indent
    - text-justify
    - text-outline
    - -ms-text-overflow
    - text-overflow
    - text-overflow-ellipsis
    - text-overflow-mode
    - text-shadow
    - text-transform
    - text-wrap
    - -webkit-text-size-adjust
    - -ms-text-size-adjust
    - letter-spacing
    - word-break
    - word-spacing
    - word-wrap
    - overflow-wrap
    - tab-size
    - white-space
    - vertical-align
    - list-style
    - list-style-position
    - list-style-type
    - list-style-image
    # Accessibility & Interactions
    - pointer-events
    - -ms-touch-action
    - touch-action
    - cursor
    - visibility
    - zoom
    - table-layout
    - empty-cells
    - caption-side
    - border-spacing
    - border-collapse
    - content
    - quotes
    - counter-reset
    - counter-increment
    - resize
    - user-select
    - nav-index
    - nav-up
    - nav-right
    - nav-down
    - nav-left
    # Background & Borders
    - background
    - background-color
    - background-image
    - -ms-filter:\\'progid:DXImageTransform.Microsoft.gradient
    - filter:progid:DXImageTransform.Microsoft.gradient
    - filter:progid:DXImageTransform.Microsoft.AlphaImageLoader
    - filter
    - background-repeat
    - background-attachment
    - background-position
    - background-position-x
    - background-position-y
    - background-clip
    - background-origin
    - background-size
    - background-blend-mode
    - isolation
    - border
    - border-color
    - border-style
    - border-width
    - border-top
    - border-top-color
    - border-top-style
    - border-top-width
    - border-right
    - border-right-color
    - border-right-style
    - border-right-width
    - border-bottom
    - border-bottom-color
    - border-bottom-style
    - border-bottom-width
    - border-left
    - border-left-color
    - border-left-style
    - border-left-width
    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-right-radius
    - border-bottom-left-radius
    - border-image
    - border-image-source
    - border-image-slice
    - border-image-width
    - border-image-outset
    - border-image-repeat
    - outline
    - outline-width
    - outline-style
    - outline-color
    - outline-offset
    - box-shadow
    - mix-blend-mode
    - filter:progid:DXImageTransform.Microsoft.Alpha(Opacity
    - -ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha
    - opacity
    - -ms-interpolation-mode
    # SVG Presentation Attributes
    - alignment-baseline
    - baseline-shift
    - dominant-baseline
    - text-anchor
    - word-spacing
    - writing-mode
    - fill
    - fill-opacity
    - fill-rule
    - stroke
    - stroke-dasharray
    - stroke-dashoffset
    - stroke-linecap
    - stroke-linejoin
    - stroke-miterlimit
    - stroke-opacity
    - stroke-width
    - color-interpolation
    - color-interpolation-filters
    - color-profile
    - color-rendering
    - flood-color
    - flood-opacity
    - image-rendering
    - lighting-color
    - marker-start
    - marker-mid
    - marker-end
    - mask
    - shape-rendering
    - stop-color
    - stop-opacity
    # Transitions & Animation
    - transition
    - transition-delay
    - transition-timing-function
    - transition-duration
    - transition-property
    - transform
    - transform-origin
    - animation
    - animation-name
    - animation-duration
    - animation-play-state
    - animation-timing-function
    - animation-delay
    - animation-iteration-count
    - animation-direction