plugins:
  #- stylelint-order
  - stylelint-scss
ignoreFiles:
  - '**/_bPlacer.scss'
  - '**/theme.css'
defaultSeverity: error
# ソート設定を読み込む
#extends: stylelint-config-recess-order
rules:
  color-no-invalid-hex: true
  font-family-no-duplicate-names: true
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  string-no-newline: true
  string-quotes: "double"
  unit-no-unknown: true
  property-no-unknown: true
  # 重複プロパティ禁止
  #declaration-block-no-duplicate-properties:
  #  - true
  #  - severity: warning
  block-no-empty: true
  comment-no-empty: true
  # 重複セレクタ禁止
  #no-duplicate-selectors:
  #  - true
  #  - severity: warning
  no-empty-source: true
  no-extra-semicolons: true
  color-named: never
  shorthand-property-no-redundant-values: true
  property-no-vendor-prefix: true
  declaration-block-single-line-max-declarations: 1
  color-hex-case: lower
  color-hex-length: short
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  function-comma-space-before: never
  function-max-empty-lines: 1
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never
  function-url-quotes: always
  function-whitespace-after: always
  number-leading-zero: never
  number-no-trailing-zeros: true
  length-zero-no-unit: true
  unit-case: lower
  value-keyword-case: lower
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  property-case: lower
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always-single-line
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always-single-line
  block-opening-brace-newline-after: always
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-colon-notation: double
  selector-type-case: lower
  selector-list-comma-newline-after: always-multi-line
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  rule-empty-line-before:
    - never
    - except: after-rule
    - ignore: after-comment
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-space-after: always
  media-query-list-comma-space-before: never
  comment-whitespace-inside: always
  indentation: 2
  linebreaks: unix
  max-empty-lines: 1
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  no-empty-first-line: true
