  bt1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/buddy-theme:cached
      - ../ACRE-theme/:/ACRE-theme:cached
    working_dir: /buddy-theme/#{theme-name}/
    ports:
      - "3001:3000"
    command: "gulp"

  bt2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/buddy-theme:cached
      - ../ACRE-theme/:/ACRE-theme:cached
    working_dir: /buddy-theme/#{theme-name}/
    ports:
      - "3002:3000"
    command: "gulp"
