  bt#{num}:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/buddy-theme:cached
      - ../ACRE-theme/:/ACRE-theme:cached
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    working_dir: /buddy-theme/#{theme-name}/
    ports:
      - "300#{num}:3000"
    command: "gulp default"

  bt#{num2}:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/buddy-theme:cached
      - ../ACRE-theme/:/ACRE-theme:cached
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    working_dir: /buddy-theme/#{theme-name}/
    ports:
      - "300#{num2}:3000"
    command: "gulp default2"

