version: 2.1
executors:
  default:
    docker:
      - image: centos:centos7
        environment:
          TZ: Asia/Tokyo

commands:
  setup:
    steps:
      # Dockerfileと同一の環境を構築する
      - run:
          yum -y update && yum -y install epel-release wget make;
          yum install -y https://rpm.nodesource.com/pub_15.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm;
          yum install nodejs -y;
          #最新のnpm install
          npm install -g npm@7.13.0;
          #最新のgulp
          npm install -g gulp@4.0.2;

          yum clean all;
          yum install -y automake autoconf libtool git make gcc*;
          #zlibのinstall
          cd /usr/local/src && \
            wget http://zlib.net/zlib-1.2.11.tar.gz && \
            tar xvzf zlib-1.2.11.tar.gz && \
            cd zlib-1.2.11 && \
            ./configure && \
            make && \
            make install;

  clone:
    steps:
      # コードを落とす
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

  npm_install:
    steps:
      # あればキャッシュを使いnpm ciする
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

jobs:
  lint:
    executor:
      name: default
    steps:
      - setup
      - clone
      - npm_install
      - run: ./.circleci/lint.sh

  build:
    executor:
      name: default
    steps:
      - setup
      - clone
      - npm_install
      - run: ./.circleci/build.sh

  output:
    executor:
      name: default
    steps:
      - setup
      - clone
      - npm_install
      - add_ssh_keys:
          fingerprints:
            - "ac:f3:69:74:e5:d3:82:42:c1:ed:df:11:5b:6f:7c:11"
      - run: ./.circleci/output.sh

workflows:
  version: 2
  lint:
    jobs:
      - lint
  build:
    jobs:
      - build
  output:
    jobs:
      - approval:
          type: approval
          filters:
            branches:
              only:
                - master
      - output:
          requires:
            - approval
          filters:
            branches:
              only:
                - master
