options:
  merge-default-rules: false
rules:
  # コロンの後のスペース
  space-after-colon: 1
  # 空セレクタ
  no-empty-rulesets: 1
  # 開き括弧の後のスペース
  space-before-brace: 1
  # 開き括弧のスタイル
  brace-style:
    # elseと閉じ括弧は同じ行に書く
    style: '1tbs'
  # セレクタとプロパティと1行で書かない
  allow-single-line: 0
  # インデントが半角スペース2つになっているか
  indentation: 1
  # カラーがキーワードで書かれていないか
  no-color-keywords: 1
  # セミコロン
  trailing-semicolon: 1
  # 末尾のスペース
  no-trailing-whitespace: 1
